services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: terraform-20241225041236553900000001.cr6suoyuuhtr.us-east-1.rds.amazonaws.com
      MYSQL_PORT: 3306
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin#123
      MYSQL_DATABASE: todo_app_db

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:

       MYSQL_DATABASE: todo_app_db
       MYSQL_USER: admin
       MYSQL_PASSWORD: Admin#123

    ports:
      - "3306:3306"

volumes:
  todo-mysql-data:
